# Generated by Django 4.1.7 on 2023-08-31 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_course_meta_description'),
        ('core', '0002_comment_phone_alter_comment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.college'),
        ),
        migrations.AddField(
            model_name='comment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.course'),
        ),
    ]
