# Generated by Django 4.1.7 on 2023-04-17 00:58

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='author')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='gallery')),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('institute_type', models.CharField(choices=[('University', 'university'), ('College', 'college')], default='college', max_length=120)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='header')),
                ('location', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('description', ckeditor.fields.RichTextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.author')),
                ('gallery', models.ManyToManyField(to='cms.gallery')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
