# Generated by Django 4.1.7 on 2023-05-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_college_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='fee_range',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='website',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
