# Generated by Django 4.1.7 on 2023-05-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_college_fee_range_college_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='star_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
