# Generated by Django 4.1.7 on 2023-06-01 18:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_college_star_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='course_fees',
            field=ckeditor.fields.RichTextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='college',
            name='placement',
            field=ckeditor.fields.RichTextField(default=None),
            preserve_default=False,
        ),
    ]
