# Generated by Django 4.1.7 on 2023-06-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='intro',
            field=models.CharField(default='hello', max_length=220),
            preserve_default=False,
        ),
    ]
