# Generated by Django 4.1.7 on 2023-06-11 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_course_intro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='placement',
            new_name='college',
        ),
    ]
