# Generated by Django 4.1.7 on 2023-07-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_college_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
