# Generated by Django 4.1.7 on 2024-02-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0012_college_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollegeCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("fees", models.CharField(max_length=120)),
                ("time", models.CharField(max_length=120)),
                ("mode", models.CharField(max_length=120)),
                ("specialisation", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="college",
            name="course",
            field=models.ManyToManyField(to="cms.collegecourse"),
        ),
    ]
