# Generated by Django 4.1.7 on 2024-02-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0013_collegecourse_college_course"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CollegeCourse",
        ),
        migrations.AddField(
            model_name="course",
            name="fee_structure",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="specialization",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="college",
            name="course",
            field=models.ManyToManyField(related_name="Course", to="cms.course"),
        ),
    ]
