# Generated by Django 4.1.7 on 2024-02-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0014_delete_collegecourse_course_fee_structure_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="duration",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
