# Generated by Django 4.1.7 on 2024-02-12 15:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0016_alter_course_course_fees_alter_course_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="college",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
