# Generated by Django 4.1.7 on 2024-02-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0017_alter_course_college"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="avg_fee",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
