# Generated by Django 4.1.7 on 2023-03-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default='Test', max_length=120),
            preserve_default=False,
        ),
    ]
